### ISSUE TITLE
Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by HydraGene** [flop25/adult_content#2]
I get this error message while having installed and activated the plugin:

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Adultcontent has a deprecated constructor in /home/haikodc90/domains/nuclearnuke.net/public_html/porn/plugins/adult_content/class.inc.php on line 4`

Can anyone please resolve this? Or at least help resolving this?

**Comment by flop25** [comment]
Hide the deprecated messages in Php or chnage your php version

**Comment by HydraGene** [comment]
Whoops, a lot of other "bugs" got solved too after I changed the PHP version. Sorry.. Thanks for your answer.
