### ISSUE TITLE
Piwigo 12.1.0 error

### ISSUE THREAD

**Issue by max-ima** [flop25/adult_content#4]
When you activate it and go to settings:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Adultcontent has a deprecated constructor in C:\AppServ\www\avs\plugins\adult_content\class.inc.php on line 4
Missing file ./plugins/adult_content/admin.php

**Comment by flop25** [comment]
Hello Thx for reporting
The plugin has been updated and the admin part should now work.
don't hesitate if there is something broken again
