### ISSUE TITLE
Now another mistake

### ISSUE THREAD

**Issue by max-ima** [flop25/adult_content#5]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Adultcontent has a deprecated constructor in C:\AppServ\www\avs\plugins\adult_content\class.inc.php on line 4

**Comment by flop25** [comment]
Hi again
I could reproduce only once and the message completely disappeared then 
That's just a 'Deprecated' message not an error. Those messages are intended for developers when testing in a dev environment. In production, php should not be set to display such messages
